### ISSUE TITLE
Do this with new version

### ISSUE THREAD

**Issue by BIGEAZY289** [Blatzar/Anime-ZoneTest#1]
Pls do this with new update this one is old

**Comment by BrenzyYT** [comment]
Yup 2.4.5 would be awesome

**Comment by Blatzar** [comment]
Give me apk and I can update, latest I could find online was 2.4.0

**Comment by Blatzar** [comment]
@BrenzyYT @BIGEAZY289 If you got the universal apk for 2.4.5 I'd be glad to update, just can't get my hands on it.

**Comment by BIGEAZY289** [comment]
I have 2.4.5 but not the universal one

**Comment by BrenzyYT** [comment]
Same I also got the apk but not the universal one,Here is the 2.4.5 apk if it does any help :).
https://drive.google.com/file/d/1RoZ4sl_l_xXnjSzKL4uNWQcJSn7NyZIj/view

**Comment by Bankaimaster999** [comment]
https://www.mediafire.com/file/0vpt6xazim5k0bc/AnimeZone.v2.4.5-universal.apk/file

@Blatzar  Here is the universal version of Anime Zone. Hope this helps ~

**Comment by Blatzar** [comment]
> https://www.mediafire.com/file/0vpt6xazim5k0bc/AnimeZone.v2.4.5-universal.apk/file
> 
> @Blatzar  Here is the universal version of Anime Zone. Hope this helps ~

Thank you, I'll update the releases soon
