### ISSUE TITLE
Take it down

### ISSUE THREAD

**Issue by spyderbibek** [Blatzar/Anime-ZoneTest#2]
bro just by bypassing github update check and changing simkl api won't make the app usable. site scraper's are the main important part of the app and the older version already got dead servers and it's impossible to fix those cause reverse engineering flutter app completely is not possible at all. No matter what sooner or later app will be unusable at all. so instead of wasting your time on this. just focus on your shiro app alot of people gonna depend on it 🙂

so i would like you to take this down. Thank You

**Comment by Ultimatinium** [comment]
Im still using it, i can also stream until now.

**Comment by pinguluk** [comment]
It's working fine for me

**Comment by Blatzar** [comment]
All taken down, it was fun while it lasted boys

> No matter what sooner or later app will be unusable at all

Might as well enjoy it as long as possible :)
